### ISSUE TITLE
Support for line breaks

### ISSUE THREAD

**Issue by riker09** [dhollerbach/github-action-send-message-to-ms-teams#1]
Hi there. And first of all thank you for your great GitHub Action. Setup was a breeze and I already push successful and failed build notification to my MS Teams channel. 👍🏻 

I noticed that line breaks are currently not supported and wanted to know wether it is possible at all and if so, if you plan on adding support for this.

Here's what I have in mind:

```yaml
name: Test Notifications

on:
  push:
    branches:
    - 'test-branch'

jobs:
  notifications:
    runs-on: ubuntu-20.04

    - name: Notify Teams
      uses: dhollerbach/actions.send-message-to-ms-teams@1.0.10
      with:
        webhook: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URL }}
        message: |
          Multiline message
          This should be on a second line
```
