### ISSUE TITLE
Issue using Github Action

### ISSUE THREAD

**Issue by gallowaystorm** [dhollerbach/github-action-send-message-to-ms-teams#2]
This is our code for our workflow file:

```yaml
      - name: MS Teams Webhook Notitfication
        if: ${{ failure() }}
        uses: dhollerbach/github-action-send-message-to-ms-teams@1.0.10
        with:
          webhook: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          message: '${{ github.event.repository.name }} has a workflow failure for ${{ github.workflow }}.'
```

This worked up until about 2 days ago.  No changes have been made but now we are getting the error:

Error: Unable to resolve actions. Repository not found : dhollerbach/github-action-send-message-to-ms-teams.
